version: "3"

networks:
    campusmap:
        external: true

volumes:
    campusmap-geoserver-data:
        external: true
    campusmap-postgres-data:
        external: true

services:
    geoserver:
        image: psuoitwdt/geoserver
        networks:
            - campusmap
        ports:
            - 8080:80
        volumes:
            - campusmap-geoserver-data:/var/geoserver/data
        links:
            - postgres:database

    postgres:
        image: mdillon/postgis:9.4
        networks:
            - campusmap
        ports:
            - 5432:5432
        volumes:
            - campusmap-postgres-data:/var/lib/postgresql/data
